"""added comment table

Revision ID: 1247d0581999
Revises: 0d69dc41ef84
Create Date: 2020-08-17 18:19:38.111404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1247d0581999'
down_revision = '0d69dc41ef84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('complaint_ibfk_2', 'complaint', type_='foreignkey')
    op.drop_constraint('complaint_ibfk_1', 'complaint', type_='foreignkey')
    op.create_foreign_key(None, 'complaint', 'user', ['complaint_by'], ['id'])
    op.create_foreign_key(None, 'complaint', 'user', ['responded_by'], ['id'])
    op.drop_constraint('roles_users_ibfk_2', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_ibfk_1', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key('roles_users_ibfk_1', 'roles_users', 'user', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('roles_users_ibfk_2', 'roles_users', 'role', ['role_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.drop_constraint(None, 'complaint', type_='foreignkey')
    op.create_foreign_key('complaint_ibfk_1', 'complaint', 'user', ['complaint_by'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('complaint_ibfk_2', 'complaint', 'user', ['responded_by'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
