"""added flagged table

Revision ID: 98f648c4eee9
Revises: 1247d0581999
Create Date: 2020-09-01 15:43:56.135383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f648c4eee9'
down_revision = '1247d0581999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('flagged_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'flagged_counter')
    # ### end Alembic commands ###
